apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: test-cluster
spec:
  instances: 3

  imageName: 'cerit.io/cloudnative-pg/postgresql:15.0'

  primaryUpdateStrategy: unsupervised

  bootstrap:
   initdb:
     database: mydb
     owner: myowner

  resources:
    requests:
      memory: "4096Mi"
      cpu: 500m
    limits:
      memory: "4096Mi"
      cpu: 1

  storage:
    size: 10Gi
    storageClass: nfs-csi
